# Generated by Django 5.1 on 2026-04-23 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='分类名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100, verbose_name='电影名')),
                ('release_year', models.IntegerField(verbose_name='上映年份')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('actors', models.CharField(max_length=200, verbose_name='主演')),
                ('region', models.SmallIntegerField(choices=[('1', '中国大陆'), ('2', '中国香港'), ('3', '中国台湾'), ('4', '美国'), ('5', '韩国'), ('6', '日本'), ('7', '其他')], verbose_name='地区')),
                ('types', models.CharField(max_length=50, verbose_name='类型')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('duration', models.CharField(max_length=50, verbose_name='时长(或集数)')),
                ('alternate_name', models.CharField(blank=True, max_length=100, verbose_name='又名')),
                ('image_url', models.URLField(blank=True, max_length=300, verbose_name='图片链接')),
                ('rate', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='评分')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('is_hot', models.BooleanField(choices=[('False', '非热门'), ('True', '热门')], default=False, verbose_name='是否热门')),
                ('is_top', models.BooleanField(choices=[('False', '不置顶'), ('True', '置顶')], default=False, verbose_name='是否置顶')),
                ('quality', models.SmallIntegerField(choices=[('1', '720P'), ('2', '1080P'), ('3', '4K')], verbose_name='清晰度')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='字幕')),
                ('update_info', models.CharField(blank=True, max_length=100, verbose_name='更新信息')),
                ('update_progress', models.CharField(blank=True, max_length=100, verbose_name='更新进度')),
                ('homepage', models.URLField(blank=True, help_text='电影主页链接', max_length=500, verbose_name='电影主页')),
                ('is_show', models.BooleanField(choices=[('False', '隐藏'), ('True', '显示')], default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='分类名')),
                ('collectors', models.ManyToManyField(blank=True, related_name='collected_movies', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
        ),
    ]
