# Generated by Django 5.1 on 2026-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '电影分类', 'verbose_name_plural': '电影分类'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_hot',
            field=models.BooleanField(choices=[(False, '非热门'), (True, '热门')], default=False, verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_show',
            field=models.BooleanField(choices=[(False, '不显示'), (True, '显示')], default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_top',
            field=models.BooleanField(choices=[(False, '不置顶'), (True, '置顶')], default=False, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.SmallIntegerField(choices=[(1, '简体中文'), (2, '英文'), (3, '日语')], max_length=100, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.SmallIntegerField(choices=[(1, '720P'), (2, '1080P'), (3, '4K')], verbose_name='清晰度'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.SmallIntegerField(choices=[(1, '中国大陆'), (2, '中国香港'), (3, '中国台湾'), (4, '美国'), (5, '韩国'), (6, '日本'), (7, '其他')], verbose_name='地区'),
        ),
    ]
