# Generated by Django 5.1 on 2026-04-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_category_options_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.SmallIntegerField(choices=[(1, '简体中文'), (2, '英文'), (3, '日语')], verbose_name='语言'),
        ),
    ]
